# So Simple Theme Configuration
# https://github.com/mmistakes/so-simple-theme

theme: jekyll-theme-so-simple

# Site Settings
title: madams.dev
description: "Solutions Architect at Databricks specializing in Healthcare & Life Sciences."
url: "https://madams.dev"
baseurl: ""
logo: /assets/img/logo-cat-guitar.png
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

# Site Author
author:
  name: Matt Adams
  picture: /assets/img/logo-cat-guitar.png
  email: probably-spam@madams.dev
  links:
    - title: GitHub
      url: https://github.com/sysopmatt
      icon: fab fa-github
    - title: LinkedIn
      url: https://linkedin.com/in/matt-adams-98ab05a3
      icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/sysopmatt
    icon: fab fa-github
  - title: LinkedIn
    url: https://linkedin.com/in/matt-adams-98ab05a3
    icon: fab fa-linkedin
  - title: Feed
    url: /feed.xml
    icon: fas fa-rss-square

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  contributions:
    output: false
  presentations:
    output: true
    permalink: /:collection/:path/

# Defaults - So Simple uses 'page' and 'post' layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: presentations
    values:
      layout: page

# Outputting
permalink: /:year-:month-:day-:title/
paginate: 10
paginate_path: /page:num/
timezone: "America/Los_Angeles"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

jekyll-archives:
  enabled:
    - tags
  layout: 'tags'
  permalinks:
    tag: '/tags/:name/'

# Exclude
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - beautiful-jekyll-theme.gemspec

# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
